-- Schema for the portfolio site content.
-- Every table is public-read only: the site ships the anon key to the browser,
-- so RLS allows SELECT and nothing else. Writes happen in the Supabase dashboard.

create table if not exists profile (
  id integer primary key default 1,
  name text not null,
  headline text not null,
  status text not null,
  location text not null,
  intro text not null,
  summary text not null,
  strengths text[] not null default '{}',
  interests text not null,
  education_degree text not null,
  education_school text not null,
  education_period text not null,
  education_note text not null,
  email text not null,
  linkedin text,
  github text,
  languages text not null,
  constraint profile_is_singleton check (id = 1)
);

create table if not exists experiences (
  id bigint generated by default as identity primary key,
  sort_order integer not null,
  role text not null,
  company text not null,
  period text not null,
  responsibilities text[] not null default '{}',
  badge text not null
);

create table if not exists photos (
  id bigint generated by default as identity primary key,
  sort_order integer not null,
  src text not null,
  alt text not null,
  caption text not null
);

create table if not exists skill_areas (
  id bigint generated by default as identity primary key,
  sort_order integer not null,
  title text not null,
  items text[] not null default '{}'
);

-- kind: 'platform' rows render with a brand logo (icon = simple-icons slug),
-- 'support' rows render as plain text chips.
create table if not exists tools (
  id bigint generated by default as identity primary key,
  sort_order integer not null,
  name text not null,
  kind text not null check (kind in ('platform', 'support')),
  icon text
);

create table if not exists certifications (
  id bigint generated by default as identity primary key,
  sort_order integer not null,
  name text not null,
  issuer text not null,
  year text not null,
  url text,
  category text not null
);

create table if not exists projects (
  id bigint generated by default as identity primary key,
  sort_order integer not null,
  title text not null,
  tools text not null,
  objective text not null,
  role text,
  metrics jsonb not null default '[]',
  certificate_url text
);

alter table profile enable row level security;
alter table experiences enable row level security;
alter table photos enable row level security;
alter table skill_areas enable row level security;
alter table tools enable row level security;
alter table certifications enable row level security;
alter table projects enable row level security;

create policy "public read" on profile for select using (true);
create policy "public read" on experiences for select using (true);
create policy "public read" on photos for select using (true);
create policy "public read" on skill_areas for select using (true);
create policy "public read" on tools for select using (true);
create policy "public read" on certifications for select using (true);
create policy "public read" on projects for select using (true);
